require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.devicons")
require("plugins.emmet")
require("plugins.treesitter")
require("plugins.tabline")
require("plugins.formatter")
require("plugins.compe")
